services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: task-api:${TAG:-latest}
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
    restart: unless-stopped
    networks:
      - monitoring-net


  prometheus:
    image: prom/prometheus:v3.14.0 
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    depends_on:
      app:
        condition: service_started
    restart: unless-stopped
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana:13.2.0 
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      prometheus:
        condition: service_healthy
    networks:
      - monitoring-net
    restart: unless-stopped


networks:
  monitoring-net:      
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
